### ISSUE TITLE
Private registry with authentication

### ISSUE THREAD

**Issue by dwelch2344** [cloudfoundry-incubator/lattice-release#123]
While I was reviewing #51 I noticed that authentication is not yet supported. Is there any ETA on when that support might drop? Even if it were just basic only that'd be a huge help

**Comment by menicosia** [comment]
Hi @dwelch2344,

Since Lattice is an 'experimental' single-user pool, we haven't prioritized many security stories. It's possible that we can prioritize this when we start the work on including a Docker registry within Lattice. If you can help by giving me a write-up about why it'd be a huge help to you, that'll help me understand your use case and evaluate that to prioritize appropriately.

Alternatively, if this is something of interest to you, of course we'd be happy to review a pull request earlier than when we had planned to do the implementation ourselves.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by sclevine** [comment]
Lattice was a Cloud Foundry project focused on delivering the Diego application scheduler into the hands of users as quickly as possible before Diego was fully integrated to Cloud Foundry. Lattice served that purpose well, but now Diego is available as the application scheduler for Cloud Foundry, and Cloud Foundry is the best way to use Diego. Therefore, Lattice is no longer actively maintained.

Apologies for not addressing your issue.

-Stephen
