### ISSUE TITLE
Feature request : dump ltc trace.

### ISSUE THREAD

**Issue by AmitRoushan** [cloudfoundry-incubator/lattice-release#132]
Hi,

We are planning to implement [84349466](https://www.pivotaltracker.com/story/show/84349466) and [84349468](https://www.pivotaltracker.com/story/show/84349468) stories about dumping trace to stdout or to provided file.

We have come up with these idea to implement it –
a) We can have local receptor client implementation which is replica of receptor client code , so that we can dump request and response immediately before sending request and after getting response as implemented by CLI .
We have done some initial implementation for this logic and it seems working fine . We are planning to place this file in ltc/receptort_client directory.  As this client implantation is exclusively for Lattice so in future we may have to sync up with receptor client. Here is quick view of trace on stdout.
 
![trace](https://cloud.githubusercontent.com/assets/9818606/7932455/01328cba-0936-11e5-975c-057d5a50ed1e.jpg)

b)  Other idea is to add trace logic in receptor client code and raise a PR to receptor repository. 
But receptor client has been used by other component such as all CC bridge modules use it.  So putting condition for enabling trace may affect the performance little bit for these modules. As we have observed  graden-linux got many conditions removed based on [performance hit] (https://www.pivotaltracker.com/n/projects/1003146/stories/88539102) . 

In both cases trace can be enable with setting environment variable.

Please provide feedback. If any of these idea looks good, we will be happy to raise PR
[#84349466]
Thanks and Regards
@AmitRoushan

**Comment by davidwadden** [comment]
We're not ready to consider forking the receptor client implementation into Lattice for this feature.

I agree though, we personally would enjoy this feature in our toolbox.  I think any way we slice it, we ought to attempt to do this right and see what the Diego team (the team that maintains [receptor](https://github.com/cloudfoundry-incubator/receptor)) thinks of supporting this functionality.  Another proposed solution (credit to @onsi) would be to inject an optional `lager.Logger` and simply log the trace directly to file (my current favorite), I didn't love the idea of the receptor simply barfing it out directly to Stdout anyway.  I checked the garden issue too, I don't see anything like logging as the root cause to their performance issues.  

We'll discuss with them what they might consider, and report back whether we should proceed with putting together an implementation.

Thanks,
David

**Comment by sclevine** [comment]
Lattice was a Cloud Foundry project focused on delivering the Diego application scheduler into the hands of users as quickly as possible before Diego was fully integrated to Cloud Foundry. Lattice served that purpose well, but now Diego is available as the application scheduler for Cloud Foundry, and Cloud Foundry is the best way to use Diego. Therefore, Lattice is no longer actively maintained.

Apologies for not addressing your issue.

-Stephen
