### ISSUE TITLE
Shutdown sequence for Spring Boot app is not triggered when using buildpack

### ISSUE THREAD

**Issue by trisberg** [cloudfoundry-incubator/lattice-release#190]
I have a Spring Boot app that I run with the buildpack support. When I stop the app using 'ltc remove' the shutdown sequence for the app isn't triggered, the app just dies. Her are logs:

````
08/28 12:12:24.00 [APP|0] 2015-08-28 16:12:23.999  INFO 17 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
08/28 12:12:24.01 [APP|0] 2015-08-28 16:12:24.009  INFO 17 --- [           main] c.s.demo.cloud.HdfsWriterApplication     : Started HdfsWriterApplication in 9.538 seconds (JVM running for 10.215)
08/28 12:12:24.26 [HEALTH|0] healthcheck passed
08/28 12:12:24.26 [HEALTH|0] Exit status 0
08/28 12:12:54.28 [HEALTH|0] healthcheck passed
08/28 12:12:54.28 [HEALTH|0] Exit status 0
08/28 12:13:24.30 [HEALTH|0] healthcheck passed
08/28 12:13:24.31 [HEALTH|0] Exit status 0
08/28 12:13:27.55 [APP|0] Exit status 255
````

Running the same app as a docker container where the Docker file is:

````
FROM java
ADD ./target/cloud-hdfs-writer-*.jar /cloud-hdfs-writer.jar
CMD exec java -jar /cloud-hdfs-writer.jar
````

and then stopping the app with 'ltc remove' I do get the correct behavior as seen in the logs:

````
08/28 12:11:14.14 [APP|0] 2015-08-28 16:11:14.143  INFO 10 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
08/28 12:11:14.17 [APP|0] 2015-08-28 16:11:14.173  INFO 10 --- [           main] c.s.demo.cloud.HdfsWriterApplication     : Started HdfsWriterApplication in 13.302 seconds (JVM running for 14.083)
08/28 12:11:14.51 [HEALTH|0] healthcheck passed
08/28 12:11:14.51 [HEALTH|0] Exit status 0
08/28 12:11:35.38 [APP|0] 2015-08-28 16:11:35.379  INFO 10 --- [       Thread-2] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@4c85dd06: startup date [Fri Aug 28 16:11:01 UTC 2015]; root of context hierarchy
08/28 12:11:35.38 [APP|0] 2015-08-28 16:11:35.383  INFO 10 --- [       Thread-2] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
08/28 12:11:35.38 [APP|0] 2015-08-28 16:11:35.385  INFO 10 --- [       Thread-2] o.s.d.h.s.s.LifecycleObjectSupport       : stopped org.springframework.data.hadoop.store.output.TextFileWriter@5864db89
08/28 12:11:35.38 [APP|0] 2015-08-28 16:11:35.385  INFO 10 --- [       Thread-2] o.s.i.endpoint.EventDrivenConsumer       : Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
08/28 12:11:35.39 [APP|0] 2015-08-28 16:11:35.389  INFO 10 --- [       Thread-2] o.s.i.channel.PublishSubscribeChannel    : Channel 'hdfs:cloud:8080.errorChannel' has 0 subscriber(s).
08/28 12:11:35.39 [APP|0] 2015-08-28 16:11:35.389  INFO 10 --- [       Thread-2] o.s.i.endpoint.EventDrivenConsumer       : stopped _org.springframework.integration.errorLogger
08/28 12:11:35.39 [APP|0] 2015-08-28 16:11:35.389  INFO 10 --- [       Thread-2] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase -2147483648
08/28 12:11:35.39 [APP|0] 2015-08-28 16:11:35.393  INFO 10 --- [       Thread-2] .s.i.r.i.RedisQueueMessageDrivenEndpoint : stopped inbound.spring.cloud.stream.output
08/28 12:11:35.39 [APP|0] 2015-08-28 16:11:35.394  INFO 10 --- [       Thread-2] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
08/28 12:11:35.39 [APP|0] 2015-08-28 16:11:35.394  INFO 10 --- [       Thread-2] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase -2147483648
08/28 12:11:35.39 [APP|0] 2015-08-28 16:11:35.394  INFO 10 --- [       Thread-2] o.s.i.endpoint.EventDrivenConsumer       : Removing {service-activator:hdfsWriter.hdfsSink.serviceActivator} as a subscriber to the 'input' channel
08/28 12:11:35.39 [APP|0] 2015-08-28 16:11:35.395  INFO 10 --- [       Thread-2] o.s.integration.channel.DirectChannel    : Channel 'hdfs:cloud:8080.input' has 0 subscriber(s).
08/28 12:11:35.39 [APP|0] 2015-08-28 16:11:35.395  INFO 10 --- [       Thread-2] o.s.i.endpoint.EventDrivenConsumer       : stopped hdfsWriter.hdfsSink.serviceActivator
08/28 12:11:35.76 [APP|0] 2015-08-28 16:11:35.764  INFO 10 --- [       Thread-2] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
08/28 12:11:35.76 [APP|0] 2015-08-28 16:11:35.764  INFO 10 --- [       Thread-2] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
08/28 12:11:35.76 [APP|0] 2015-08-28 16:11:35.766  INFO 10 --- [       Thread-2] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
08/28 12:11:35.89 [APP|0] Exit status 143
````

**Comment by damon-pivotal** [comment]
@trisberg The actual shutdown process for docker apps vs buildpack apps is identical, so it looks like the discrepancy here is between java-buildpack-built droplets and "FROM java" docker images. I'm guessing that the start command generated by the java-buildpack differs from `exec java -jar /cloud-hdfs-writer.jar` in some meaningful way, but it's also possible that you're using different JREs in each case, etc.

We noticed that the Docker java image defaults to Java 8. To rule out the potential JRE difference, can you try this with `FROM java:7` in the Docker file and pass `-e 'JBP_CONFIG_OPEN_JDK_JRE=jre: { version: 1.7.0_+ }'` to build-droplet? (Or the opposite, you can pass version: 1.8 to the buildpack.)

**Comment by trisberg** [comment]
From what I see everything is using Java 8 - docker, ltc+docker, ltc+buildpack and cf+buildpack

The only environment where the shutdown call isn't made is ltc+buildpack

how can I see the startup command used for ltc+buildpack?

the one used for cf+buildpack is logged as:
App my-ltc-app was started using this command `SERVER_PORT=$PORT $PWD/.java-buildpack/open_jdk_jre/bin/java -cp $PWD/.:$PWD/.java-buildpack/spring_auto_reconfiguration/spring_auto_reconfiguration-1.7.0_RELEASE.jar -Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh -Xmx768M -Xms768M -XX:MaxMetaspaceSize=104857K -XX:MetaspaceSize=104857K -Xss1M org.springframework.boot.loader.JarLauncher`

I've pushed an app to GitHub that you can use to test - it logs "*** STOP Called" during the shutdown. It is here: https://github.com/trisberg/my-ltc-app

Same app is also in a docker image named springdeveloper/my-ltc-app

**Comment by trisberg** [comment]
If I leave out the `exec` part of the docker start command I get the same behavior as I see with ltc+buildpack. 

I changed `CMD exec java -jar /my-ltc-app.jar` to  `CMD java -jar /my-ltc-app.jar`

and then the container shutdown is not initiated, the process just dies.

**Comment by crawsible** [comment]
Hey @trisberg, this feature doesn't seem to be supported by the java-buildpack by default.

You're right that the missing `exec` call is the culprit. The java buildpack generates a config-heavy start command that looks like this:
```
CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-1.1.1_RELEASE -memorySizes=metaspace:64m.. -memoryWeights=heap:75,metaspace:10,stack:5,native:10 -totMemory=$MEMORY_LIMIT) && SERVER_PORT=$PORT $PWD/.java-buildpack/open_jdk_jre/bin/java -cp $PWD/.:$PWD/.java-buildpack/spring_auto_reconfiguration/spring_auto_reconfiguration-1.10.0_RELEASE.jar  -Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh $CALCULATED_MEMORY org.springframework.boot.loader.JarLauncher
```
When we stopped your example app after deploying it to PWS (with Diego) using this default start command, the exit handler didn't fire.

However, when `exec` is manually inserted into the default start command:
```
..._LIMIT) && export SERVER_PORT=$PORT && exec $PWD/.java-buildpack/open_...
```
the exit handler fires:
```
2015-09-08T17:34:39.87-0400 [CELL/0]     OUT Exit status 0
2015-09-08T17:34:39.87-0400 [APP/0]      OUT 2015-09-08 21:34:39.874  INFO 18 --- [       Thread-2] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2015-09-08T17:34:39.87-0400 [APP/0]      OUT 2015-09-08 21:34:39.875  INFO 18 --- [       Thread-2] com.springdeveloperdemo.LifecycleBean    : *** STOP Called
2015-09-08T17:34:39.87-0400 [APP/0]      OUT 2015-09-08 21:34:39.879  INFO 18 --- [       Thread-2] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2015-09-08T17:34:39.96-0400 [APP/0]      OUT Exit status 143
```

So this is an issue with the Java buildpack, but we're not sure if this could be considered a bug.

Perhaps we could help you more effectively if you told us your use case? We haven't considered any use cases for instance-level exit handling, since Lattice supports running multiple instances of a given app, and you likely would not want an exit handler to fire multiple times upon scaling down your app.

**Comment by trisberg** [comment]
Hi,

The use case is a new spring-cloud-stream module writing to HDFS. It holds data written in a buffer that is periodically flushed to HDFS. On shutdown the close logic flushes the remaining data and closes the file. If the shutdown isn't triggered the data in the buffer is lost.

**Comment by trisberg** [comment]
So, since the same buildpack seems to work fine on CF pre-Diego I assume that the container Diego is using behaves differently when we launch a Java process compared to the old DEA style.

**Comment by menicosia** [comment]
If y'all want, you can easily test Diego behavior on PWS. I presume you can
simulate a failure by simply scaling the app up and down?

BTW, Thomas, outside of addressing this bug: is it a concern that
not-infrequently, containers will disappear without warning, for instance
when a VM or host computer crashes?



-- 
--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
  mnicosia@pivotal.io
  c: 650-796-2948

**Comment by trisberg** [comment]
@menicosia I just tried on PWS and I see the same issue with the shutdown not happening when the app stops. Is all of PWS now running on Diego?

As for the containers disappearing, that could be a problem if the app is unaware of it being shutdown, seems that any in-flight data could be lost. We'll have to take this into consideration.

**Comment by ematpl** [comment]
Hi, @trisberg, 

No, Diego is still opt-in on PWS, and by default your app will run on the DEAs. You can use the Diego CLI plugin to inspect whether your app is running on Diego, or look for the value of the `diego` field in the output of `cf curl /v2/apps/$(cf app APP-NAME --guid)`.

Thanks,
Eric, CF Runtime Diego PM

**Comment by nebhale** [comment]
We are currently testing the Java Buildpack against the Diego exposed on PWS.  So as far as our test suite is concerned, everything is working.  What we don't do is test JVM shutdown hooks.  So, we'll look into whether it's possible to automate that test.

**Comment by sclevine** [comment]
This is a table of platforms / buildpacks that fail to send a SIGTERM to apps appropriately:
```
                   | PWS  | PWS+Diego | Lattice 0.4.0
-----------------------------------------------------
Default Java BP    | Fail | Fail      | Fail
Default JBP + exec | Pass | Pass      | Pass
benhale/master     | Pass | Pass      | Pass
benhale/exec-test  | Pass | Pass      | Pass
Ruby BP            | Pass | Pass      | Pass
Ruby BP + '&&'     | Fail | Fail      | Fail
```

- Pass means that we were able to trap the SIGTERM and print a message.
- Fail means that the app started successfully, but no SIGTERM trap message was printed.
- The Java buildpack trials all used `trisberg/my-ltc-app`.
- The Ruby buildpack trial used a `rails new`d app with a trap on SIGTERM.
- The "Default JBP + exec" trial used a manually modified start command that had `exec` inserted.
- The "Ruby BP + '&&'" trial added a `sleep 1 &&` to the start command of the "Ruby BP" trial.
- The "benhale/exec-test" trial used a forked version of the Java buildpack that was 192 commits behind master and included an `exec` in the start command.
- The "benhale/master" trial used a forked version of the Java buildpack that was 192 commits behind master.

After some discussion with the Diego team, we've determined that this is an issue with both Diego and the existing DEAs. A complex start command (which has the launching bash process as its parent) does not receive a SIGTERM when an instance is terminated. A simple start command (without `&&`, `|`, etc), will be `exec`d by bash automatically, which explains why many other buildpacks do not have this issue. 

The current Java buildpack has this issue because it recently included a complex start command. The `benhale` forks of the buildpack do not have the issue, because they are 192 commits behind master.

We will close this issue once an appropriate issue is opened with Diego or Garden. We added [a tracker story](https://www.pivotaltracker.com/story/show/103593000) to upgrade Diego/Garden when a fix becomes available.

**Comment by trisberg** [comment]
Just following up on this, was there ever any change made to address this issue?

**Comment by ematpl** [comment]
Hi, @trisberg,

The Diego team has https://www.pivotaltracker.com/story/show/103541132 in its backlog to send TERM signals to any processes remaining in the container after the processes invoked by RunActions are individually signaled with TERM and then KILLed. This should allow any processes orphaned by their parent processes an opportunity to exit gracefully before being killed abruptly on destruction of the container.

Additionally, @nebhale and I have been discussing the ramifications of introducing an `exec` before the `java` command in the start command that the Java buildpack generates, as discussed in this issue. On a related note, I've added a https://www.pivotaltracker.com/story/show/108724524 to the Diego tracker about documenting the operational consequences of invoking buildpack-app start commands with `bash -c`, so that buildpack authors and CF app users can have a better understanding of their interface to the CF system.

Thanks,
Eric

**Comment by nebhale** [comment]
@trisberg, This change is in place and in `master`.  Can you please double check that the proper signals are getting to the application?

**Comment by trisberg** [comment]
Hi,

@nebhale, I tested my app with the latest commit and the app context is
closed on shutdown, so from my end this fixes the issue.

Thanks for the fix, any idea when the next buildpack release is scheduled
for?

-Thomas

**Comment by nebhale** [comment]
Not really, before the New Year certainly, but nothing more specific than that.  Any date that you'd like (considering that `master` will continue to work for you)?

**Comment by sclevine** [comment]
This issue was addressed upstream.
