### ISSUE TITLE
Error fetching image metadata: HTTP code: 404

### ISSUE THREAD

**Issue by pako-grape** [cloudfoundry-incubator/lattice-release#195]
I' am trying to create app from private docker registry:
```vim
ltc create my-redis 52.20.92.72.xip.io:5000/my-redis
```
and getting an error:
<b>Error fetching image metadata: HTTP code: 404</b>

There are steps I've done:
1) Launch an ubuntu instance on AWS and install docker there.
2) Certificates
```vim
# generate (on server):
openssl req -x509 -nodes -newkey rsa:2048 -keyout certs/domain.key -out certs/domain.crt

# add to system (the same on client machine):
cp certs/domain.crt /usr/share/ca-certificates
dpkg-reconfigure ca-certificates
```
3) Run registry
```vim
docker run -p 5000:5000 --restart=always --name registry \
    -v `pwd`/certs:/certs \
    -e SEARCH_BACKEND=sqlalchemy \
    -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
    -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
    registry:2.0
```

And I can push/pull images to this registry by docker:
```vim
docker push 52.20.92.72.xip.io:5000/my-redis
docker pull 52.20.92.72.xip.io:5000/my-redis
```
<b>So why I can't do ltc create?</b>
I can add, there are an errors in registry:
<b>http: TLS handshake error from 52.28.218.18:56516: remote error: bad certificate</b>
From time to time there is also this error (when pushing image for example):
<b>http: TLS handshake error from MY_IP:51350: remote error: unknown certificate authority</b>

**Comment by davidwadden** [comment]
I think you ran into a problem with the default [**redis**](https://hub.docker.com/_/redis/) image that was pushed to [DockerHub](https://hub.docker.com/) on 09/10/2015.  We're not sure about the underlying root cause yet, but for the time being, we advised people to deploy `redis:3.0.1` (See  [troubleshooting](http://lattice.cf/docs/troubleshooting/#can-39-t-ltc-create-redis-from-dockerhub) page).  However, I re-tested it and it seems to be working (without any change on our end and the push date remaining the same).

To respond to this, we documented a temporary workaround with [[#103257172](https://www.pivotaltracker.com/story/show/103257172)], but we have [[#103738400](https://www.pivotaltracker.com/story/show/103738400)] scheduled to remove the workaround now that it seems to be working again.

Can you try again and let us know what you experience?

**Comment by pawel2-grape** [comment]
Hmm... I think you didn't understand my problem...
I cannot create app from <b>private registry</b>.
But this private registry seems to be good because I can pull the image with docker.
Creating apps from Docker Hub is working, only from private registry not.

I did what you suggest, I pushed redis:3.0.1 to private registry and problem is the same.

**Comment by davidwadden** [comment]
Sorry about that - I thought the error message was related to another issue.

Okay, I hadn't tried following our private docker registry instructions in some time, and noticed it was out of date.  We just finished [[#103737020](https://www.pivotaltracker.com/story/show/103737020)] and our private docker registry [instructions](http://lattice.cf/docs/private-docker-registry/) should be better now.

I haven't tested it myself, but take a look and give us any feedback you may have.

@davidwadden

**Comment by pawel2-grape** [comment]
Hmm... Looks like I forgot to add that my lattice is deployed by terraform :(
But even if I change garden-linux.conf on each lattice cell and restart garden (or even whole machine), problem is the same:
Error fetching image metadata: HTTP code: 404

One more important thing: certificate is added to the system, so I can pull image <b>without</b> changing any flags for docker daemon. So... Lattice should be able to do the same without adding -insecureDockerRegistryList flag to garden-linux.conf

**Comment by davidwadden** [comment]
Okay so I think the error you're seeing is wholly unrelated to the cluster configuration.  It would help to see more of the command you're trying to do.  Is this public code you have on Github I could try to reproduce with?  The error is likely `ltc` attempting to connect to your Docker Registry to fetch the image metadata and maybe having issues.

If you're willing, contact me via email and let me try to connect to your terraform cluster to reproduce this issue.  This is not functionality we've explicitly tested with although I _think_ it should work.

**Comment by davidwadden** [comment]
First off, Lattice running against a self-signed registry in Terraform is not a supported thing yet.  But, we're discussing how to improve the local docker experience and private registries will be better supported in some time.  The [document](http://lattice.cf/docs/private-docker-registry/) I gave you earlier specifically applies to vagrant deployments.  I did test it this morning with [[#103737020](https://www.pivotaltracker.com/story/show/103737020)] and that does work.

However, with your help, I was able to narrow it down to [docker_metadata_fetcher.go:60](https://github.com/cloudfoundry-incubator/lattice/blob/master/ltc/docker_runner/docker_metadata_fetcher/docker_metadata_fetcher.go#L60) throwing the error.  This means we're not even getting far enough to submit this back to the cluster for garden-linux to attempt to pull the layers and bring up the container.  This is failing when the CLI attempts to determine metadata about the docker image, specifically the `EXPOSE`, `WORKDIR` and `ENTRYPOINT` directives.

I don't think we're getting far enough to even submit this back to the cluster to pull the layers.  The Lattice CLI (`ltc`) queries the registry using the 

I ran `docker logs <registry_container>` and saw the following from the `ltc` attempting to fetch the metadata from the registry:

```
205.178.83.96 - - [23/Sep/2015:21:57:29 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "Go 1.1 package http"
time="2015-09-23T21:57:29Z" level=info msg="response completed" http.request.host="52.0.36.67.xip.io:5000" http.request.id=c4a07e5a-71f6-4f31-b03d-2dede6344e7a http.request.method=GET http.request.remoteaddr="205.178.83.96:58335" http.request.uri="/v2/" http.request.useragent="Go 1.1 package http" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.934526ms http.response.status=200 http.response.written=2 instance.id=fac7c236-3d72-4324-96b7-4d4ec83f0b1b version=v2.1.1
205.178.83.96 - - [23/Sep/2015:21:57:29 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "Go 1.1 package http"
205.178.83.96 - - [23/Sep/2015:21:57:29 +0000] "GET /v1/repositories/my-redis/images HTTP/1.1" 404 19 "" "Go 1.1 package http"
time="2015-09-23T21:58:37Z" level=info msg="response completed" http.request.host="52.0.36.67.xip.io:5000" http.request.id=fb820435-fca1-4507-aab0-2eb9f3350005 http.request.method=GET http.request.remoteaddr="205.178.83.96:58983" http.request.uri="/v2/" http.request.useragent="Go 1.1 package http" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.854472ms http.response.status=200 http.response.written=2 instance.id=fac7c236-3d72-4324-96b7-4d4ec83f0b1b version=v2.1.1
```

I hacked around the `ltc` [code](https://github.com/cloudfoundry-incubator/lattice/blob/master/ltc/docker_runner/command_factory/docker_runner_command_factory.go#L231-L236) by subbing in:

`imageMetadata := &docker_metadata_fetcher.ImageMetadata{}`

And then trying to create with the below command (passing the metadata explicitly):

```
○ → ltc create my-redis 52.0.36.67.xip.io:5000/my-redis -w /data -p 6379 -- /entrypoint.sh redis-server
Monitoring the app on port 6379...
Creating App: my-redis
........09/23 17:23:12.37 [APP|0] Successfully created container
09/23 17:23:13.26 [APP|0] Creating container
......09/23 17:23:19.33 [APP|0] Successfully created container
09/23 17:23:18.90 [APP|0] Creating container
.09/23 17:23:19.30 [APP|0] Successfully created container
..................................................09/23 17:24:12.49 [APP|0] Creating container
.09/23 17:24:12.91 [APP|0] Successfully created container
..............^C
```

**garden-linux** reports some of the following through the logs:
```
[rep|cell-1]           [ERROR]   09/23 17:23:19.49 4.1018.2.1.2   rep.depot-client.run-container.run.setup.download-step.fetch-failed
                                                                  Download failed: Status code 404
                                                                  {"cacheKey":"","guid":"my-redis-bd769ebf-a345-47de-45a4-c9f3658584a4","to":"/tmp","user":"vcap"}
``` 

What's weird is when I do get the cluster to attempt to download the docker image, garden-linux reports getting 404s but I don't see the equivalent error in the registry logs:
```
time="2015-09-23T23:00:52Z" level=info msg="response completed" http.request.host="52.0.36.67.xip.io:5000" http.request.id=17300c1b-da17-4576-b8eb-391dde7e75ed http.request.method=GET http.request.remoteaddr="54.175.231.124:58071" http.request.uri="/v2/" http.request.useragent="docker/1.7.0 go/go1.4.2 git-commit/f07f542 kernel/3.13.0-61-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.955342ms http.response.status=200 http.response.written=2 instance.id=fac7c236-3d72-4324-96b7-4d4ec83f0b1b version=v2.1.1
54.175.231.124 - - [23/Sep/2015:23:00:52 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.7.0 go/go1.4.2 git-commit/f07f542 kernel/3.13.0-61-generic os/linux arch/amd64"
time="2015-09-23T23:00:52Z" level=info msg="response completed" http.request.host="52.0.36.67.xip.io:5000" http.request.id=adafcb39-0123-4178-979a-df249dc25d46 http.request.method=GET http.request.remoteaddr="54.175.231.124:58072" http.request.uri="/v2/" http.request.useragent="docker/1.7.0 go/go1.4.2 git-commit/f07f542 kernel/3.13.0-61-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=2.027375ms http.response.status=200 http.response.written=2 instance.id=fac7c236-3d72-4324-96b7-4d4ec83f0b1b version=v2.1.1
```

I saved off the logs from the registry at https://gist.github.com/davidwadden/56a5f5923c3b53b44fcb
Notable times:
23/Sep/2015:21:54-23/Sep/2015:21:58 - `ltc` with metadata lookup


I took a step back here and made sure the problem was related to the self-signed certs as I suspect.  I ran an insecure registry on your AWS registry (on port 5001), and configured **garden-linux** to allow insecure communication with that.  I ran into the same 404 from the normal `ltc`:

```
○ → ltc create my-redis3 52.0.36.67:5001/my-redis -r -w /data -p 6379 -- /entrypoint.sh redis-server
Error fetching image metadata: HTTP code: 404
```

But had success using the hacked version without the metadata lookup:

```
○ → ltc create my-redis2 52.0.36.67:5001/my-redis -r -w /data -p 6379 -- /entrypoint.sh redis-server
Monitoring the app on port 6379...
Creating App: my-redis2
.09/23 17:45:35.74 [APP|0] Successfully created container
.09/23 17:45:36.09 [APP|0] 14:C 23 Sep 22:45:36.093 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
09/23 17:45:36.09 [APP|0] 14:M 23 Sep 22:45:36.093 * Increased maximum number of open files to 10032 (it was originally set to 1024).
09/23 17:45:36.09 [APP|0]                 _._
09/23 17:45:36.09 [APP|0]            _.-``__ ''-._
09/23 17:45:36.09 [APP|0]       _.-``    `.  `_.  ''-._           Redis 3.0.1 (00000000/0) 64 bit
09/23 17:45:36.09 [APP|0]   .-`` .-```.  ```\/    _.,_ ''-._
09/23 17:45:36.09 [APP|0]  (    '      ,       .-`  | `,    )     Running in standalone mode
09/23 17:45:36.09 [APP|0]  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
09/23 17:45:36.09 [APP|0]  |    `-._   `._    /     _.-'    |     PID: 14
09/23 17:45:36.09 [APP|0]   `-._    `-._  `-./  _.-'    _.-'
09/23 17:45:36.09 [APP|0]  |`-._`-._    `-.__.-'    _.-'_.-'|
09/23 17:45:36.09 [APP|0]  |    `-._`-._        _.-'_.-'    |           http://redis.io
09/23 17:45:36.09 [APP|0]   `-._    `-._`-.__.-'_.-'    _.-'
09/23 17:45:36.09 [APP|0]  |`-._`-._    `-.__.-'    _.-'_.-'|
09/23 17:45:36.09 [APP|0]  |    `-._`-._        _.-'_.-'    |
09/23 17:45:36.09 [APP|0]   `-._    `-._`-.__.-'_.-'    _.-'
09/23 17:45:36.09 [APP|0]       `-._    `-.__.-'    _.-'
09/23 17:45:36.09 [APP|0]           `-._        _.-'
09/23 17:45:36.09 [APP|0]               `-.__.-'
09/23 17:45:36.09 [APP|0] 14:M 23 Sep 22:45:36.094 # Server started, Redis version 3.0.1
09/23 17:45:36.09 [APP|0] 14:M 23 Sep 22:45:36.094 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
09/23 17:45:36.09 [APP|0] 14:M 23 Sep 22:45:36.094 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
09/23 17:45:36.09 [APP|0] 14:M 23 Sep 22:45:36.094 * The server is now ready to accept connections on port 6379
09/23 17:45:36.19 [APP|0] {"timestamp":"1443048336.196844816","source":"sshd","message":"sshd.started","log_level":1,"data":{}}
09/23 17:45:36.54 [HEALTH|0] healthcheck passed
09/23 17:45:36.55 [HEALTH|0] Exit status 0

my-redis2 is now running.
```

So, generally, I don't think I have a quick workaround for you to make this work.  We'll need to do some work on our end to support self-signed certificates.  I didn't test an insecure registry running on AWS, but you may have better luck getting an unsigned registry to work.

I don't have a timeline when we might be able to perform this feature request yet.  But, this was very educational for me to learn about self-signed registries and I'll work on trying to bring this functionality to Lattice.

@davidwadden

**Comment by pawel2-grape** [comment]
Thanks a lot for debug this.
I hope that this will be working soon:)

**Comment by llambda** [comment]
I just ran into this issue, FYI. not sure what it means or what to do

**Comment by sclevine** [comment]
Lattice was a Cloud Foundry project focused on delivering the Diego application scheduler into the hands of users as quickly as possible before Diego was fully integrated to Cloud Foundry. Lattice served that purpose well, but now Diego is available as the application scheduler for Cloud Foundry, and Cloud Foundry is the best way to use Diego. Therefore, Lattice is no longer actively maintained.

Apologies for not continuing to address your issue.

-Stephen
