### ISSUE TITLE
Breaking digitalocean support

### ISSUE THREAD

**Issue by dwatrous** [cloudfoundry-incubator/lattice-release#224]
Release 0.6.0 fixed one of my biggest barriers to using lattice to server sites from multiple domains (issue #137).

Unfortunately this release also breaks digitalocean support, which is what drove me to lattice in the first place. When I found that I couldn't deploy cloudfoundry to digitalocean, I came to lattice. I appreciate that there is a great deal of investment in BOSH at pivotal and I notice in the release notes that lattice is still committed to making sure "Users do not and will not need to understand or use BOSH to deploy Lattice".

I think I understand that BOSH combines the feature set of a stack like "terraform + ansible + nagios". BOSH prefers to cache the output of the "terraform + ansible" step as an image that can then be deployed. That will provide certain speed benefits when it comes time to provision/deploy a new node, but it limits the environments where I can run cloudfoundry and has now begun to impact lattice.

At the last cloudfoundry conference in Santa Clara I had conversations with several people around the difficulty of using BOSH and accommodating a larger variety of IaaS providers. I know that's the direction for pivotal even as other vendors, such as HP, move away from BOSH in favor of other deployment mechanisms with their cloudfoundry distributions.

In your discussions around future deployment approaches for both lattic and cloudfoundry, I wanted to put my voice behind a composed stack of tools like "terraform + ansible + nagios". There are a lot of tools that can be used for those three functions and I think there would be value in moving toward separate projects for each function rather than BOSH.

As of release 0.6.0 lattice is again unavailable because I primarily deploy to digitalocean.

**Comment by davidwadden** [comment]
First off, thank you for the thoughtful response.  We don't have a lot of insight into what people are doing with Lattice today.  In order to get feedback on the "retooled cluster" sooner, we elected to release without DigitalOcean support.  We're asking our users to voice what platforms are important to them (hence the [survey](http://goo.gl/forms/z33xBoLaeQ)), since every additional platform we support is a lot for us to maintain.  For every additional platform we choose to support, it takes away time we could be adding features.

I'm curious.  What is it about DigitalOcean that's attractive?  We've had this debate as a team a couple times -- _if_ we broke support forever, would you not be able / willing to move to AWS instead?  We can never make DigitalOcean _that_ secure, as it doesn't allow network-level ACLs or virtualized networking -- things we intend to bring to AWS at some point.

I'm not sure how you deploy Cloud Foundry without BOSH.  We tried doing it before with hand-rolled Upstart scripts, and it proved to be a futile endeavor to try and keep up to date.  Re-writing the provisioning / control scripts around the CF microservices is a non-trivial effort.  To that end, I don't see where Ansible makes sense in the Lattice stack.  However, Terraform is still our deployment tool of choice for Lattice and Nagios wouldn't be entirely unreasonable, although "cell-level" OS metrics may be of limited value.  CF is working on exposing APIs to give visibility into internal metrics generally, and Lattice may see that one day.

With the **v0.6.0** release of Lattice, we've come up with a way to tokenize the configs specific to the BOSH-provisioned VM instance, which splits the "terraform" and "ansible" portions of the provisioning process.  We then snapshot that and use as the base image from the terraform configs.  The terraform provisioner then invokes the install-from-tar to install and configure Lattice-specific components.

We still need to figure out how to engineer Lattice to work on platforms that do not support public base images (like DigitalOcean).  One possible solution would be to have the user "build" Lattice in order to create the appropriate base images on their DigitalOcean account, update the terraform configs to reference that private base image (snapshot), then run the standard Lattice installer on top of that.  It may be that we use the "[transfer snapshots between accounts](https://www.digitalocean.com/company/blog/easily-transfer-snapshots-between-accounts/)" functionality and transfer the base image from our CI account.

Would you still use Lattice if you had to run our "baking" scripts that run BOSH against your DigitalOcean account to create the initial private base image (snapshot)?  We strive to keep to the statement in the notes, but this might be a slight exception (although we think we can keep the experience minimal).

@davidwadden

**Comment by dwatrous** [comment]
@davidwadden My reasons for choosing digitalocean have been price, simplicity and VM size. I have modest needs for most of my small scale web applications that are accommodated by a 1cpux512MB server.

It's possible that I could revisit my approach using Lattice and have fewer larger servers for all my websites, although I still have some concerns about container security in multi-tenant environments.

Stackato produces a VM image that is self-contained and includes every possible role. That one image can be configured at instance creation to function as any role. What Stackato is missing is the IaaS integration for automatic provisioning and monitoring for platform self-healing. These are taken care of with BOSH.

What I was suggesting is with a BOSH replacement is based on my understanding that bosh does three things
 1. BOSH provides an IaaS abstraction, like terraform or heat, to create new servers. 
 2. BOSH provides configuration (image creation from a stemcell), like Ansible. Unlike ansible, this produces an image for the IaaS
 3. BOSH monitors servers it creates and keeps the platform healthy by repeating steps 1 and 2 as necessary.

It seems that a trio of tools, like terraform, Ansible and Nagios could provide the same functionality that exists in BOSH today. My idea is that these tools would be easier to use than BOSH and even more approachable. I'm not sure I see how this could make it harder to keep cloudfoundry up to date.

Where BOSH's configuration mechanism produces an image, Ansible can work on any image. Terraform can create servers with any base image and pass that off to Ansible. This also makes it easy to come up with alternate scenarios like a local Vagrant deploy configured by Ansible. It's my understanding that a major thrust behind Lattice in the first place was trying to make it easier to setup an environment where people can contribute to the codebase for cloudfoundry. Using three separate tools like this also conforms to the non-PaaS cloud native deployment approaches.

I know how committed Pivotal is to BOSH, so I'm not expecting to change anyone's position on this.

For small organizations, the operational overhead of dealing with BOSH is too high. I love the simplicity of "push"ing apps to cloudfoundry or lattice, but I don't have time to work with BOSH. I'm already using some of the tools I've mentioned, like terraform and heat, Ansible, puppet, chef and nagios, new relic, munin, etc. to deploy my applications. It may be I'm a candidate for your hosted solution.

I'll keep an eye on Lattice and may consider using it on AWS. I'm going to close this ticket since it's really not actionable right now. Thanks for your response.
