### ISSUE TITLE
Failed to retrieve preconfiguration file

### ISSUE THREAD

**Issue by fordaz** [cloudfoundry-incubator/lattice-release#225]
Getting the following error while trying to build Lattice on VirtualBox with `./build -only=virtualbox-iso`

The command hangs at
```
...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available...
```

The build continues to run after a logging into virtual box console and selecting one of the pre-config options.

Thanks,
@leochu and @fordaz

![image](https://cloud.githubusercontent.com/assets/4836732/10738360/5480e6f8-7bd4-11e5-8cc7-28af4755d153.png)

**Comment by davidwadden** [comment]
Thanks for the report.  I have a laptop this happens on as well.  Hasn't been an issue since it always works on CI.

(at least we have an environment to reproduce on) 

Can follow [[#106677354](https://www.pivotaltracker.com/story/show/106677354)] to get the latest status, but we'll look into it right away.

**Comment by fordaz** [comment]
As an additional data point, we observed this behavior on three out of four iMacs, the three machines having the issue were sprout-wrapped, the other one was not.
