### ISSUE TITLE
Lattice 0.6.0 Vagrantfile doesn't download lattice.tgz via proxy on Windows

### ISSUE THREAD

**Issue by mbechauf** [cloudfoundry-incubator/lattice-release#226]
Used to work without a problem with 0.5.0 and lower. 

Vagrant version 1.7.2 on Windows 

It appears that the change from curl to Net::HTTP is the culprit. The only way I get it to work is to pass the proxy address and port explicitly. The http_proxy and https_proxy environment variables are being ignored otherwise.

    def download_lattice_tgz(url)
      uri = URI(url)
    #  Net::HTTP.start(uri.host, uri.port, p_addr: "proxy.pal.sap.corp", p_port: 8080, use_ssl:   uri.scheme == 'https' ) do |http|
       Net::HTTP.start(uri.host, uri.port, "proxy", 8080, use_ssl: uri.scheme == 'https' ) do    |http|

I don't know Ruby that well so I'm not sure what's going on, but I found a hint here: https://www.jethrocarr.com/2014/08/14/ruby-nethttp-proxies/

> Turns out that this proxy transversal only takes place if Net::HTTP is invoked as an object, however if you invoke one of it’s methods directly it ignores the proxy environmentals entirely.

So, with HTTP.start, the environment variables are being ignored and `vagrant up` fails like this:

    Local lattice.tgz not found, downloading...
    There was an error loading a Vagrantfile. The file being loaded
    and the error message are shown below. This is usually caused by
    a syntax error.

    Path: C:/Users/i007509/lattice/lattice-bundle-v0.6.0/vagrant/Vagrantfile
    Message: getaddrinfo: No such host is known.

**Comment by davidwadden** [comment]
Thanks, that's definitely a possibility as we made our `Vagrantfile` work on Windows.  I've prioritized [[#106711812](https://www.pivotaltracker.com/story/show/106711812)] for the team to review, and we'll look into cutting a patch release soon as we can.

@davidwadden

**Comment by mbechauf** [comment]
I'd be surprised if that would be a Windows-only issue, though. 
-----Original Message-----

**Comment by davidwadden** [comment]
@mbechauf - ok i misread this issue from the bat, I thought we regressed on proxy functionality on the supporting OSX/Linux when I responded at first.  As to Windows, we don't support Windows yet.  We made a change with [[#98709384](https://www.pivotaltracker.com/story/show/98709384)] [736f069](https://github.com/cloudfoundry-incubator/lattice-release/commit/736f06959fa20031484b5fce749dfdded56cbaea) that switched to platform-independent logic that had the potential to break **v0.6.0**, but we tested today against Windows and OS X/Linux and neither had an issue.

I'm not convinced this is a proxy issue, further, Windows proxy support wasn't specifically listed so how did it break?  Were you using cygwin or gitbash or something that gave you `curl` ? 

[Stack Overflow](http://stackoverflow.com/questions/14454058/getting-error-getaddrinfo-no-such-host-is-known-socke-terror-with-mechaniz) seems to indicate a DNS issue.  What happens when you `nslookup proxy.pal.sap.corp` ?

Any other details you can provide us with?

**Comment by mbechauf** [comment]
Yes, with 0.5.0 I simply had a version of curl off of the cygwin tools on my machine, and it worked without a problem. `lattice.tgz` was downloaded, the HTTP_PROXY and HTTPS_PROXY environment variables were set, and curl recognized them. After that, `vagrant up` worked without a problem and Lattice was up.

With the change in 0.6.0, these environment variables don't seem to work any more. 

`proxy.pal.sap.corp` is the regular SAP corporate proxy, and it resolves without a problem in `nslookup proxy.pal.sap.corp`. All my other apps work just fine, so this is not a corporate connectivity problem.

The moment I hardcode the proxy in the Net:HTTP call, everything works fine

    Net::HTTP.start(uri.host, uri.port, "proxy.pal.sap.corp", 8080, use_ssl: uri.scheme == 'https' ) do |http|

You are saying you tested this under Windows and in a proxied environment and it worked for you?

**Comment by davidwadden** [comment]
I had to look a little closer on this one.  I spot-checked access logs coming through Fiddler and noticed once the cluster was up, everything I expected to see traversed the proxy.  However, you're having the problem just downloading the `lattice.tgz` -- but once that's downloaded, I /think/ everything should work from that point forward.

So as a temporary workaround, download the [`lattice-v0.6.0.tgz`](https://lattice.s3-us-west-2.amazonaws.com/lattice-tgz/lattice-v0.6.0.tgz) into the `vagrant/` folder directly and rename it to `lattice.tgz`.

```bash
$ pwd
/c/.../lattice-bundle-v0.6.0/vagrant

$ curl -o lattice.tgz https://lattice.s3-us-west-2.amazonaws.com/lattice-tgz/lattice-v0.6.0.tgz
```

So, to be clear, Windows is not yet a supported platform.  Our next release is slated to have "experimental support" for Windows, but aside from the proxy issue `vagrant up` works on Windows already (as of **v0.6.0**).  We'll treat [[#106711812](https://www.pivotaltracker.com/story/show/106711812)] as a new feature as and prioritize ahead of our upcoming Windows release.

Also, report back whether that workaround worked or not.  It's hard to shut off direct outbound internet traffic from a Windows box to truly verify, but judging from the [`Vagrantfile`](https://github.com/cloudfoundry-incubator/lattice-release/blob/master/vagrant/Vagrantfile#L145), it looks like once you have the tarball, it stops trying to download it.

**Comment by davidwadden** [comment]
Our latest [nightly build](https://lattice.s3.amazonaws.com/nightly/index.html) **v0.6.0-34-g32acfa9** downloads `lattice.tgz` from behind a proxy properly.

Check it out!
David

**Comment by mbechauf** [comment]
Cool - thanks, will check it out.

**Comment by mbechauf** [comment]
Had to take a few days off for other issues, and focused my energy on getting Lattice up and running. Will check out the suggested nightly build fix soon. 

But for now, I think I got another proxy/Windows issue in 0.6.0. Sorry that I keep having these issues. I'm well aware of the spotty support for Windows, but I'm trying to use Lattice as an educational CF and container tool at SAP, and most of use just have only Windows boxes. 

I tried to start the test app via `ltc create lattice-app cloudfoundry/lattice-app`, and continue to get `Failed to create container` messages. I used `ltc dl` to find out what is going on, and ran into the same issue as @amaltson with #223. I think I figured this one out which is that between 0.5.0 and 0.6.0 the `http_proxy` spelling was changed and is now all lowercase when the `vagrant-proxyconf` is used. Others must have had the same problem, because with SHA: 55c934cbd666636e380f15e1943a4e0e68adab76 both upper and lowercase is now supported.

Well, Windows does not support lowercase variables, and I was able to get past this issue by starting `vagrant up` through a Cygwin shell and setting proxy variables in lowercase. Now `ltc dl` works, and it gives a good hint what the problem is: The Docker image metadata cannot be accessed through the proxy.

`[rep|lattice-colocated-0] [ERROR]   11/12 05:22:02.38 5.95.1         rep.depot-client.run-container.create-in-garden.failed-creating-garden-container
repository_fetcher: GetRepositoryData: could not fetch image cloudfoundry/lattice-app from registry index.docker.io: Get https://index.docker.io/v1/repositories/cloudfoundry/lattice-app/images: dial tcp: lookup index.docker.io: no such host`

Not sure what the problem is. Wasn't the whole point of the `vagrant-proxyconf` that these issues should disappear?

**Comment by davidwadden** [comment]
So, first, I strongly recommend getting our latest [nightly build](https://lattice.s3.amazonaws.com/nightly/index.html) if you're using Windows.  A lot of changes have been made since [**v0.6.0**](https://github.com/cloudfoundry-incubator/lattice-release/releases/tag/v0.6.0) specifically for Windows compatibility, and we now publish a binary `ltc.exe` that can be curl'ed off the cluster.

```
curl -O http://receptor.<system_domain>/v1/sync/windows/ltc.exe
.\ltc.exe -v
```  

Second, read my [comment](https://github.com/cloudfoundry-incubator/lattice-release/issues/223#issuecomment-156095112) on #223.  Also read our [proxy setup](http://lattice.cf/docs/proxy/) directions on the website.  I just want to be aware there 1) is a "cluster proxy" (based on env vars at `vagrant up`) and 2) a `ltc` proxy (based on env vars in scope when running ltc).  You can list environment variables before those commands in Powershell with `Get-Item Env:`

I believe the reporter on #223 was having issues with `no_proxy` set in `ltc`.  He needed `ltc` to talk to DockerHub using his proxy but needed to avoid the proxy for connecting to Lattice.

In your case, I think you should do two things:
1. Modify your `Vagrantfile` to add your custom system domain to `no_proxy` at [`Vagrantfile:16-21`](https://github.com/cloudfoundry-incubator/lattice-release/blob/master/vagrant/Vagrantfile#L16-L21)
1. Set your `no_proxy` to include your custom system domain when running `ltc`

**Comment by davidwadden** [comment]
On second thought, are you setting the `LATTICE_DOMAIN` env var as your "custom system domain" when you `vagrant up` ?  That should address the first 1. above ( :fist: markdown ) and vagrant should set the `no_proxy` appropriate for the cluster proxy.

**Comment by mbechauf** [comment]
`ltc` on Windows? Wow, has hell just frozen over ? ;-) Seriously, I'm glad you guys are investing. I've had a lot of pain with Lattice whereas Kubernetes was a snap on Windows. Yes, I've installed from the package and if you are comfortable with the nightly builds, I can certainly use it. Just didn't want to introduce any more instability due to nightly builds. 

Regarding your questions: Yes `LATTICE_DOMAIN` is set, and the `no_proxy` value is set before calling `ltc`. Even though I hacked together a Windows version of `ltc` with the help from the HP Cloud folks, in this case I callled `ltc` from the Lattice host. 

Nevertheless, it's not working. Please note that the error message `lookup index.docker.io: no such host` also came through on the server logs by `ltc dl` and not on the `ltc` shell. 

I held back with documenting some of the custom domain work I've done to avoid cluttering my messages, but since there is no DNSMasq-like software for Windows, I had to come up with a solution. However, I better document it in #223 which is where I think we'll discuss custom domain setups.

**Comment by sclevine** [comment]
Lattice was a Cloud Foundry project focused on delivering the Diego application scheduler into the hands of users as quickly as possible before Diego was fully integrated to Cloud Foundry. Lattice served that purpose well, but now Diego is available as the application scheduler for Cloud Foundry, and Cloud Foundry is the best way to use Diego. Therefore, Lattice is no longer actively maintained.

Apologies for not continuing to your issue.

-Stephen
