### ISSUE TITLE
Deploy Lattice on custom hosts

### ISSUE THREAD

**Issue by mfilotto** [cloudfoundry-incubator/lattice-release#232]
Hi,
Would be awesome to deploy Lattice on our existing CentOS VM.
Thanks

**Comment by davidwadden** [comment]
Lattice has a minimum kernel requirement of 3.19 to support its containerization features. I don't believe CentOS has reached that yet.

Check with `uname -a` and let me know if that's the case or not.

**Comment by mfilotto** [comment]
It's still on `3.10.0-229.el7.x86_64` 
Thanks for your help

**Comment by davidwadden** [comment]
So with a kernel upgrade, this could be done by configuring the null provisioner for packer in our [config](https://github.com/cloudfoundry-incubator/lattice-release/blob/master/vagrant/lattice.json) (assuming colocated) and running the build to provision the server.  The file would need to be modified to install the dependencies using `yum` instead of `apt-get`, so it's possible but we're not planning to support that at this time.

**Comment by mfilotto** [comment]
ok thanks for your answers
